### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by menagerie198** [wjgoarxiv/obsidian-supsub#1]
I'd love to use your plugin, but I am getting a `Plugin ID mismatch` warning/failure.

**Comment by wjgoarxiv** [comment]
Thanks for reporting the issue with the Plugin ID mismatch. I'm looking into this right now and will keep you updated soon. Apologies for any inconvenience caused, and I appreciate your patience :)

**Comment by wjgoarxiv** [comment]
I must note here that the Supsub plugin is NOT officially registered with the community plugins. As such, you'll need to manually place the `obsidian-supsub` folder in the `.obsidian/plugins/` directory. To do this, navigate to the `.obsidian/plugins/` folder and enter the following command in your terminal:

```shell
git clone https://github.com/wjgoarxiv/obsidian-supsub.git
```

Afterward, open the Preference tab by hitting `cmd + ,`. Proceed to the `Community plugin` tab, where you will find the Installed plugins section. You should be able to load the `Obsidian SupSub` plugin normally by clicking the refresh button.

If you continue to encounter the Plugin ID mismatch warning, please don't hesitate to inform me.

**Comment by menagerie198** [comment]
I'm confused... What is this?...
![image](https://github.com/wjgoarxiv/obsidian-supsub/assets/7330436/8e5cbd71-9f3d-4351-bebd-aacc8af924b0)

**Comment by menagerie198** [comment]
I got SupSub installed successfully via BRAT :)

**Comment by wjgoarxiv** [comment]
I'm glad you installed it well.

**Comment by wjgoarxiv** [comment]
Note that the installation failure issue has been solved. You can now install `SupSub` from the `Community Plugin` tab normally. :)
