### ISSUE TITLE
Cursor location with nothing selected

### ISSUE THREAD

**Issue by ShawnNPD** [wjgoarxiv/obsidian-supsub#3]
It would be awesome if when you used the hotkeys with no text selected it then moved the cursor to between the sup/sub tags. So if you want to make the tag before typing the text you can just do the hotkey and then immediately start typing. If there *is* something highlighted then it acts as it normally does. 

This would make it act similarly to when doubles are created when you type a [ or ( ,etc. It makes the start and end brackets, but keeps your cursor in between. Thanks for the great plugin!

**Comment by wjgoarxiv** [comment]
Hi ShawnNPD, 

I wanted to personally thank you for your fantastic suggestion regarding the SupSub plugin. I'm excited to let you know that I've implemented the feature you requested in the latest version (`v1.0.2`)!

### New Feature Highlights:
- **Cursor Positioning**: Now, when you use the hotkeys with no text selected, the cursor will automatically be placed between the `<sup>` or `<sub>` tags, so you can start typing immediately. This makes the workflow smoother and more intuitive, just like you described!

I truly appreciate your input and the time you took to help enhance the plugin. If you have any more suggestions or encounter any issues, please don’t hesitate to let me know.

Thanks again for your contribution!

Best regards,
_wjgoarxiv_

**Comment by ShawnNPD** [comment]
Sweet! I will use it all the time. Nice work!
