### ISSUE TITLE
Asking for an Improvement 

### ISSUE THREAD

**Issue by lpokt** [wjgoarxiv/obsidian-supsub#4]
Hi!  
This is a fantastic plugin. It performs exactly as needed, and that's great. However, there's one improvement I'd love to see: **Hiding the tags upon insertion and only showing them when hovering over the text formated with `sub` & `sup` tags .**

To clarify, here’s how the plugin currently works:

1. I format the selected text with `sub` & `sup` tags.
2. It displays the tags like this: `<sub>selected text</sub>`.
3. Only if I click elsewhere on the page does it show the text as subscript.

What I'd like it to do:

1. I format the selected text with `sub` & `sup` tags.
2. It instantly shows the selected text as subscript without displaying the tags.
3. The tags should only appear if I click on the subscripted text.

**Comment by wjgoarxiv** [comment]
Dear @lpokt,

Thank you for your patience and for sharing your insightful feedback on the plugin. I apologize for the delayed response.

I’ve carefully reviewed your suggestion regarding the immediate rendering of `<sub>` and `<sup>` tags upon insertion, with the tags themselves hidden and only revealed upon hovering over the formatted text. While this feature would indeed enhance the user experience, implementing it presents certain challenges within the current capabilities of Obsidian’s editor.

Obsidian’s editor, particularly in _Live Preview_ mode, is designed to display Markdown and HTML tags as they are typed, rendering them only after the user moves the cursor away from the current line. This behavior ensures that users can see and edit the raw Markdown or HTML code directly.

To achieve the functionality you’re describing—where the tags are hidden immediately upon insertion and the formatted text is displayed instantly—would require altering the core behavior of Obsidian’s editor. Such modifications are beyond the scope of a plugin, as they would necessitate changes to the editor’s fundamental rendering process.

However, with the current version of the SupSub plugin, you can achieve the desired formatting by following these steps:

- [x] __Apply Superscript or Subscript Formatting.__ Use the designated hotkeys to wrap your selected text with `<sup>` or `<sub>` tags. For example, pressing `Ctrl + Alt + =` (or `Option + Cmd + =` on macOS) will wrap the selected text with `<sup>` tags.
- [x] __Move the Cursor Away.__ After applying the formatting, move the cursor to another line or click elsewhere in the document. This action prompts Obsidian to render the tags, displaying the text as superscript or subscript accordingly.

I appreciate your understanding and am grateful for your valuable input. If you have any further suggestions or questions, please feel free to share them.

Best regards,
@wjgoarxiv

**Comment by lpokt** [comment]
Thank you for your detailed and thoughtful response to my suggestion. I truly appreciate the time and effort you’ve put into explaining the challenges and providing a workaround.

I’d like to share an observation that might offer a potential solution that worth exploring.

The **Typing Assistant** plugin in Obsidian provides functionality that resembles what I’m suggesting. When activing the **Select Option** and using its bold option, the selected text is instantly displayed as bold without showing the `**` Markdown syntax. The `**` only becomes visible when I click on the formatted text.

I hope that it might be technically possible to achieve similar behavior for `<sub>` and `<sup>` tags in the SupSub plugin. While I understand that adapting such functionality could involve unique challenges, I believe exploring this approach might yield a more seamless experience for users.

I hope this example proves helpful, and I look forward to seeing how the plugin evolves. Please let me know if there’s anything further I can do to support or clarify this suggestion.

**Comment by wjgoarxiv** [comment]
Hi @lpokt,

Thank you for your valuable suggestion! I'm excited to inform you that version **`1.0.3`** now includes pop-up buttons for generating `<sup>` and `<sub>` tags, inspired by your feedback. This should provide a smoother and more seamless experience like the Typing Assistant plugin. If you have further ideas or feedback on this update, please let me know. 

Best regards,  
@wjgoarxiv

**Comment by lpokt** [comment]
Thank you so much for your efforts in improving this plugin.

I wanted to clarify my request regarding the <sup> and <sub> tags. Specifically, I’m hoping the tags won’t appear immediately after insertion when using the pop-up buttons.

To make my point clearer, here’s a [video](https://imgur.com/a/Mg4c1ud) demonstrating what I mean.

In the video, you’ll notice {in the Using plugin section} how the Typing Assistant plugin handles the insertion of bold syntax. When I use its buttons to apply bold formatting, the ** Markdown syntax is instantly hidden, and the bold text is displayed right away—without requiring me to click elsewhere on the page.

I believe achieving a similar functionality for <sup> and <sub> tags in the SupSub plugin would greatly enhance its usability and make the user experience smoother.

Thank you once again for considering this suggestion and for your dedication to enhancing this project.

**Comment by wjgoarxiv** [comment]
Dear @lpokt 

I've updated the new version (v1.0.4)! So please download it, and check whether the **instant formatting feature** (not visualizing either `<sup></sup>` or `<sub></sub>` tags) is running smoothly in your environment. 

If there aren't any troubles, I'll close this issue. So please let me know:)

**Comment by lpokt** [comment]
Awesome! I just tried the new version (v1.0.4), and it works perfectly—exactly how I imagined it from the start!

The instant formatting feature is smooth, and no issues so far. Thank you so much for your efforts and quick updates—really appreciate it! Everything's running flawlessly now, Great job!

**Comment by wjgoarxiv** [comment]
Dear @lpokt

Thank you for your feedback! 
I'm pleased to hear that **Supsub** works perfectly for you and that the instant formatting feature meets your expectations.

Feel free to reach out if you have any more suggestions or run into any other issues. 

Best regard,
@wjgoarxiv
