### ISSUE TITLE
Display issues with new supsub buttons

### ISSUE THREAD

**Issue by Comprehensive-Jason** [wjgoarxiv/obsidian-supsub#5]
Plugin version 1.0.3 added supsub buttons which pop up anytime text is highlighted. I think this is a great feature for users who don't want to use keyboard shortcuts, but the buttons do display weirdly and get in the way sometimes. 

When I select and then right-click on text, the buttons cover up part of the right-click menu. 
![image](https://github.com/user-attachments/assets/8dada3ed-7d65-4dd5-8266-f7eea35852ab)

Also, if text is selected and you bring up the command pallette, the buttons stay on screen but end up in the upper-right corner of the screen. 
![image](https://github.com/user-attachments/assets/05ef8606-b57c-4aca-ab11-9613d3d00581)

I think a good remedy would be to make these buttons part of the right-click menu. Alternatively, you could add a way to disable them from popping up in plugin settings.

**Comment by wjgoarxiv** [comment]
Dear @Comprehensive-Jason 

First of all, I apologize for the inconvenience.
Thank you for bringing this issue.
I will update the feature as soon as possible :)

**Comment by wjgoarxiv** [comment]
Dear @Comprehensive-Jason 

Please download the **new version (v1.0.4)**. 
You can toggle the `Enable Popup Buttons` option, so you might be able to avoid overlapping the buttons with the right-click menus. 

If you don't experience any troubles, I'll close this issue:) 
Therefore, please let me know.

**Comment by Comprehensive-Jason** [comment]
The new options work great, thanks!

**Comment by wjgoarxiv** [comment]
Thank you for your comments:) Have a nice day.
