### ISSUE TITLE
Text disappears in editing mode…

### ISSUE THREAD

**Issue by Scrimie** [wjgoarxiv/obsidian-supsub#6]
Hey, I just updated the plugin to the most recent update. When I did, I continued editing my notes and quickly discovered that if I added or deleted more than about 4 spaces my equations (where I used the plugin) would start disappearing. Any more than 4 spaces and each additional space would remove a pre-existing character. When I switch from the editor to the reader everything was normal. Any help would be much appreciated. 
 - Thanks, Edan :)

**Comment by wjgoarxiv** [comment]
Hi @Scrimie (Edan),

I’m really sorry for the inconvenience you’re experiencing with the latest plugin update. To help me identify and resolve the issue more effectively, could you please provide **a `GIF` or `MP4` recording that captures the problem** in detail? 

This will allow me to better understand what’s happening and work on a fix as quickly as possible.

Thank you for your assistance!

Best regards,
@wjgoarxiv

**Comment by Scrimie** [comment]
Hey @wjgoarxiv, I was working on my notes today and everything is running perfectly. I was playing around with using obsidian’s insert math block feature yesterday when I started having problems. When I tried using the feature today I didn’t have any issues. Sorry for the late reply I was travelling for most of today. 

Happy holidays and thanks for your help! 
@Scrimie

**Comment by wjgoarxiv** [comment]
Glad to hear everything’s working well! No worries about the delay. Happy holidays! 🎉
